### ISSUE TITLE
Specify where resources are located when running the project.

### ISSUE THREAD

**Issue by DynamicField** [novelrt/NovelRT-Gradle-Plugin#3]
NovelRT loads resources in a specific and configurable folder. But the Java app needs to know where that resource folder is located.

The resource location can be specified with a Java property: `dev.novelrt.resources`. That property can be set with an argument such as `-Ddev.novelrt.resources=C:\some_resources`.

We need to apply this before the `run` task.

**Comment by jeuxjeux20** [comment]
Fixed in commit https://github.com/novelrt/NovelRT-Gradle-Plugin/commit/4d9793e433579d8cd9fdc85692bd44c073fab323
